LuXuzDev/SGL

build/classes/interfaz_usuario/trabajador_autoescuela/inicio-trabajador.fxml, src/interfaz_usuario/administrador/autoescuela/inicio-admin-autoescuela.fxml, src/interfaz_usuario/administrador/medico/inicio-admin-medico.fxml, src/interfaz_usuario/administrador/sistema/inicio-administrador.fxml, src/interfaz_usuario/login/login.fxml, src/interfaz_usuario/medico/inicio-medico.fxml, src/interfaz_usuario/trabajador_autoescuela/controladores/ControladorTrabajadorAutoescuela.java, src/interfaz_usuario/trabajador_autoescuela/inicio-trabajador.fxml, src/interfaz_usuario/trabajador_centro/inicio-trabajador-centro.fxml
se agregaron los iconos de los menus inicio de todos los roles y se realizo la transicion de el menu _trabajador autoescuela
=> feat(Transicion,Agregar iconos):Trabajador autoescuela,menus de inicio

build/classes/interfaz_usuario/administrador/autoescuela/inicio-admin-autoescuela.fxml, build/classes/interfaz_usuario/administrador/medico/inicio-admin-medico.fxml, build/classes/interfaz_usuario/administrador/sistema/inicio-administrador.fxml, build/classes/interfaz_usuario/login/login.fxml, build/classes/interfaz_usuario/medico/inicio-medico.fxml, build/classes/interfaz_usuario/trabajador_autoescuela/controladores/estilos/Estilos.css, build/classes/interfaz_usuario/trabajador_autoescuela/inicio-trabajador.fxml, build/classes/interfaz_usuario/trabajador_centro/inicio-trabajador-centro.fxml, src/gestor_interfaces/GestorEscenas.java, src/interfaz_usuario/administrador/autoescuela/inicio-admin-autoescuela.fxml, src/interfaz_usuario/administrador/medico/inicio-admin-medico.fxml, src/interfaz_usuario/administrador/sistema/inicio-administrador.fxml, src/interfaz_usuario/login/controladores/ControladorLogin.java, src/interfaz_usuario/login/login.fxml, src/interfaz_usuario/medico/controladores/ControladorMedico.java, src/interfaz_usuario/medico/inicio-medico.fxml, src/interfaz_usuario/trabajador_autoescuela/controladores/ControladorTrabajadorAutoescuela.java, src/interfaz_usuario/trabajador_autoescuela/controladores/estilos/Estilos.css, src/interfaz_usuario/trabajador_autoescuela/inicio-trabajador.fxml, src/interfaz_usuario/trabajador_centro/inicio-trabajador-centro.fxml
Funcion de transicion en gestor escenas ,funcion de tecla enter en login y archivo css para progress bar de trabajador autoescuela
=> feat():Funcion de transicion ,funcion de tecla enter en login y archivo css para progress bar

build/classes/interfaz_usuario/recursos_compartidos/estilos/EstilosProgressBar.css, build/classes/interfaz_usuario/recursos_compartidos/estilos/EstilosProgressBarVertical.css, build/classes/interfaz_usuario/trabajador_autoescuela/inicio-trabajador.fxml, src/interfaz_usuario/recursos_compartidos/estilos/EstilosProgressBar.css, src/interfaz_usuario/trabajador_autoescuela/controladores/ControladorTrabajadorAutoescuela.java, src/interfaz_usuario/trabajador_autoescuela/inicio-trabajador.fxml
-Progressbar vertical
-Reemplazaado boton nombre por label
-listener en progressbar
-controlador de ancho de texto
-agregado icono en ventana
=> feat(MenuTrabajadorAutoescuela)

src/interfaz_usuario/administrador/medico/controladores/ControladorAdministradorMedico.java, src/interfaz_usuario/administrador/medico/inicio-admin-medico.fxml, src/interfaz_usuario/administrador/sistema/controladores/ControladorAdministradorSistema.java, src/interfaz_usuario/administrador/sistema/inicio-administrador.fxml, src/interfaz_usuario/trabajador_centro/controladores/ControladorTrabajadorCentro.java, src/interfaz_usuario/trabajador_centro/inicio-trabajador-centro.fxml
Se realizaron todas las transciones para los menus de administrador y del trabajador del centro
=> feat: transiciones (admin, trabajador centro)

build/classes/interfaz_usuario/administrador/medico/inicio-admin-medico.fxml, src/gestor_interfaces/GestorEscenas.java, src/interfaz_usuario/trabajador_autoescuela/controladores/ControladorTrabajadorAutoescuela.java
se hizo  comentarios en las funciones del Controlador y se movio la funcion al gestor de escenas de el salto de linea
=> refactor(TrabajadorAutoescuela)

build/classes/interfaz_usuario/administrador/autoescuela/inicio-admin-autoescuela.fxml, build/classes/interfaz_usuario/administrador/medico/inicio-admin-medico.fxml, build/classes/interfaz_usuario/administrador/sistema/inicio-administrador.fxml, build/classes/interfaz_usuario/login/login.fxml, build/classes/interfaz_usuario/medico/inicio-medico.fxml, build/classes/interfaz_usuario/trabajador_autoescuela/inicio-trabajador.fxml, build/classes/interfaz_usuario/trabajador_centro/inicio-trabajador-centro.fxml, src/gestor_interfaces/GestorEscenas.java, src/interfaz_usuario/administrador/autoescuela/controladores/ControladorAdministradorAutoescuela.java, src/interfaz_usuario/administrador/autoescuela/inicio-admin-autoescuela.fxml, src/interfaz_usuario/administrador/medico/controladores/ControladorAdministradorMedico.java, src/interfaz_usuario/administrador/medico/inicio-admin-medico.fxml, src/interfaz_usuario/administrador/sistema/controladores/ControladorAdministradorSistema.java, src/interfaz_usuario/administrador/sistema/inicio-administrador.fxml, src/interfaz_usuario/login/controladores/ControladorLogin.java, src/interfaz_usuario/login/login.fxml, src/interfaz_usuario/medico/controladores/ControladorMedico.java, src/interfaz_usuario/medico/inicio-medico.fxml, src/interfaz_usuario/recursos_compartidos/estilos/EstilosCheckBox.css, src/interfaz_usuario/trabajador_autoescuela/controladores/ControladorTrabajadorAutoescuela.java, src/interfaz_usuario/trabajador_autoescuela/inicio-trabajador.fxml, src/interfaz_usuario/trabajador_centro/controladores/ControladorTrabajadorCentro.java, src/interfaz_usuario/trabajador_centro/inicio-trabajador-centro.fxml
Trabaje en todos los menus tuve q cambiar la funcion de los colores de botones y arreglar los codigos,puse iconos en las ventanas con su titulo y hice lo del salto de linea ,arregle cosas esteticas de los menus botones mal puestos y separador corto ,puse todas las progres bar verticales en el proyecto , volvi a darle funcionamiento en el login al enter y añadi un nuevo estilo para los checkbox de gestion de licencia
=> fix(FuncionamientoBotonesColor)

build/classes/interfaz_usuario/administrador/sistema/inicio-administrador.fxml, src/interfaz_usuario/administrador/autoescuela/inicio-admin-autoescuela.fxml, src/interfaz_usuario/administrador/medico/inicio-admin-medico.fxml, src/interfaz_usuario/administrador/sistema/inicio-administrador.fxml, src/interfaz_usuario/medico/inicio-medico.fxml, src/interfaz_usuario/recursos_compartidos/estilos/EstilosCheckBox.css, src/interfaz_usuario/trabajador_autoescuela/inicio-trabajador.fxml, src/interfaz_usuario/trabajador_centro/inicio-trabajador-centro.fxml
arregle diseño de los checkbox, arregle posicion de botones en gestion examenes y agregue botones de cerrar sesion en tidis los menus
=>  fix(CheckBox)

build/classes/interfaz_usuario/administrador/sistema/inicio-administrador.fxml, build/classes/interfaz_usuario/recursos_compartidos/errores/mensaje-error.fxml, src/interfaz_usuario/administrador/sistema/controladores/ControladorAdministradorSistema.java, src/logica/centro/consultas/ConsultaCentro.java, src/logica/centro/implementaciones/ServiciosCentro.java, src/logica/entidad/modelos/EntidadRelacionada.java, src/logica/examen/consultas/ConsultaExamen.java, src/logica/examen/implementaciones/ServiciosExamenes.java, src/logica/examen/modelos/Examen.java, src/logica/examen_medico/consultas/ConsultaExamenMedico.java, src/logica/examen_medico/implementaciones/ServiciosExamenesMedicos.java, src/logica/examen_medico/modelos/ExamenMedico.java, src/logica/persona/modelos/Aprendiz.java, src/logica/persona/modelos/Persona.java, src/logica/usuario/modelos/Usuario.java
se agregaron las consultas de obtener todos de examenes medicos ,teoricos ,practicos y el obtener centro q es solo uno
=> feat(ConsultasObtenerTodos)

build/classes/interfaz_usuario/administrador/sistema/inicio-administrador.fxml, src/gestor_tablas/GestorTablas.java, src/interfaz_usuario/administrador/sistema/controladores/ControladorAdministradorSistema.java, src/interfaz_usuario/administrador/sistema/inicio-administrador.fxml, src/interfaz_usuario/recursos_compartidos/estilos/EstilosTableView.css, src/logica/examen/consultas/ConsultaExamen.java, src/logica/examen/modelos/Examen.java, src/logica/examen_medico/implementaciones/ServiciosExamenesMedicos.java, src/logica/examen_medico/modelos/ExamenMedico.java, src/logica/persona/modelos/Persona.java
se realizo la visual en el menu de examenes del administrador donde se ven todos
=> feat(VisualizacionExamenesAdministrador)

build/classes/interfaz_usuario/administrador/autoescuela/inicio-admin-autoescuela.fxml, src/gestor_tablas/GestorTablas.java, src/interfaz_usuario/administrador/autoescuela/controladores/ControladorAdministradorAutoescuela.java, src/interfaz_usuario/administrador/autoescuela/inicio-admin-autoescuela.fxml, src/logica/examen/consultas/ConsultaExamen.java, src/logica/usuario/consultas/ConsultasUsuario.java
se llenaron las tablas en examen teorico y practico en el administrador autoescuela
=> feat(VisualTablaExamenesTeoricos,Practicos)

build/classes/interfaz_usuario/administrador/autoescuela/inicio-admin-autoescuela.fxml, src/interfaz_usuario/administrador/autoescuela/inicio-admin-autoescuela.fxml
se arreglaron los tamaños de las columnas en el menu adminautoescuela de los examenes teoricos y practicos
=> fix(TamañoDelasColumnasenAdminauto)

build/classes/interfaz_usuario/recursos_compartidos/menus/menu_auxiliares/ver-mas/menu-ver-mas-conductores.fxml, nbproject/project.properties, src/gestor_tablas/GestorTablas.java, src/interfaz_usuario/administrador/sistema/controladores/ControladorAdministradorSistema.java, src/interfaz_usuario/administrador/sistema/inicio-administrador.fxml, src/logica/entidad/consultas/ConsultasEntidad.java, src/logica/infraccion/consultas/ConsultasInfraccion.java, src/logica/infraccion/implementaciones/ServicioInfraccion.java, src/logica/infraccion/modelos/Infraccion.java, src/logica/licencia/implementaciones/ServicioLicencia.java, src/logica/licencia/modelos/Licencia.java, src/logica/persona/modelos/Persona.java
ya se visuliza la tabla entidades con los datos de la base de datos
=> feat Conectar Tabla Entidades con la base de datos

src/gestor_tablas/GestorTablas.java, src/interfaz_usuario/administrador/sistema/controladores/ControladorAdministradorSistema.java, src/interfaz_usuario/administrador/sistema/inicio-administrador.fxml, src/logica/entidad/consultas/ConsultasEntidad.java, src/logica/entidad/implementaciones/ServicioEntidad.java
ya se visualiza la tabla autoescuela con los datos de la base de datos
=> feat conectar tabla autoescuela con la base de datos

src/gestor_tablas/GestorTablas.java, src/interfaz_usuario/administrador/sistema/controladores/ControladorAdministradorSistema.java, src/interfaz_usuario/administrador/sistema/inicio-administrador.fxml, src/logica/entidad/consultas/ConsultasEntidad.java, src/logica/entidad/implementaciones/ServicioEntidad.java
ya se visualiza las tablas de clinicas con los datos de la base de datos
=> feat: Conectar Tabla Cinicas con la base de datos

src/gestor_tablas/GestorTablas.java, src/interfaz_usuario/administrador/sistema/controladores/ControladorAdministradorSistema.java, src/interfaz_usuario/administrador/sistema/inicio-administrador.fxml, src/logica/infraccion/consultas/ConsultasInfraccion.java, src/logica/infraccion/modelos/Infraccion.java, src/logica/persona/modelos/Conductor.java, src/logica/persona/modelos/Persona.java
ya se visualiza la tabla de infracciones con los datos de la base de datos
=> feat:  conectar tabla Infracciones con la base de datos

src/gestor_tablas/GestorTablas.java, src/interfaz_usuario/administrador/sistema/controladores/ControladorAdministradorSistema.java, src/interfaz_usuario/administrador/sistema/inicio-administrador.fxml, src/logica/infraccion/consultas/ConsultasInfraccion.java, src/logica/licencia/consultas/ConsultasLicencia.java, src/logica/licencia/modelos/Licencia.java
ya se visualiza en la tabla licencia los datos de la base de datos
=> feat: Conectar Tabla Licencia con la base de datos

src/interfaz_usuario/administrador/sistema/inicio-administrador.fxml
Se arreglo el tamaño de las columnas de las tablas: -Entidades
-Autoescuelas
-Clinicas
-Infracciones
-Licencias
=> style: Arreglo del tamaño de las columnas de las tablas

src/logica/licencia/consultas/ConsultasLicencia.java
Se arreglo une error en el metodo ObtenerlicenciaPorID y ya funciona correctamente
=> fix: metodo ObtenerLicenciaPorID

src/gestor_tablas/GestorTablas.java, src/interfaz_usuario/administrador/sistema/inicio-administrador.fxml, src/logica/infraccion/consultas/ConsultasInfraccion.java, src/logica/infraccion/modelos/Infraccion.java, src/logica/licencia/consultas/ConsultasLicencia.java, src/logica/licencia/modelos/Licencia.java, src/logica/persona/consultas/ConsultasPersona.java, src/logica/persona/implementaciones/ServicioConductor.java
Se arreglaron las clases Infracion y Licencia tanto en sus atributos y constructores asi como las consultas para obtener las tablas de estas 2 clases
=> fix: Correcion de las las clases infraccion y Licencia

build/classes/interfaz_usuario/administrador/medico/inicio-admin-medico.fxml, src/gestor_interfaces/GestorEscenas.java, src/gestor_tablas/GestorTablas.java, src/interfaz_usuario/administrador/medico/controladores/ControladorAdministradorMedico.java, src/interfaz_usuario/administrador/medico/inicio-admin-medico.fxml
se arreglo error de instancia en el menu ver mas examenes medicos de el admin medico
=> fix(menuvermasExamenMedicoAdminMedico):

build/classes/interfaz_usuario/recursos_compartidos/menus/menu_auxiliares/ver-mas/menu-ver-mas-infraccion.fxml, src/gestor_interfaces/GestorEscenas.java, src/gestor_tablas/GestorTablas.java, src/interfaz_usuario/recursos_compartidos/menus/controladores/ControladorVerMasInfracciones.java, src/interfaz_usuario/recursos_compartidos/menus/menu_auxiliares/ver-mas/menu-ver-mas-infraccion.fxml
ya funcionan los ver mas de la tabla infracciones con los datos de la base de datos
=> feat: Ya funciona el ver mas de la tabla infracciones

src/gestor_tablas/GestorTablas.java, src/interfaz_usuario/administrador/autoescuela/controladores/ControladorAdministradorAutoescuela.java, src/interfaz_usuario/administrador/medico/controladores/ControladorAdministradorMedico.java, src/interfaz_usuario/administrador/sistema/controladores/ControladorAdministradorSistema.java, src/interfaz_usuario/medico/controladores/ControladorMedico.java, src/interfaz_usuario/trabajador_autoescuela/controladores/ControladorTrabajadorAutoescuela.java
se hizo refactor en la clase gestor tablas entera camelCase
=> refactor(GestorTablas)

build/classes/interfaz_usuario/medico/inicio-medico.fxml, build/classes/interfaz_usuario/medico/menu_auxiliares/ver-mas/menu-ver-mas-examenes-medicos.fxml, src/interfaz_usuario/administrador/autoescuela/controladores/ControladorAdministradorAutoescuela.java, src/interfaz_usuario/administrador/medico/menu_auxiliares/registrar/registrar-examen-medico.fxml, src/interfaz_usuario/medico/controladores/ControladorMedico.java, src/interfaz_usuario/medico/inicio-medico.fxml, src/interfaz_usuario/medico/menu_auxiliares/registrar/registrar-examen-medico.fxml, src/interfaz_usuario/medico/menu_auxiliares/ver-mas/menu-ver-mas-examenes-medicos.fxml, src/interfaz_usuario/recursos_compartidos/menus/menu_auxiliares/registrar/registrar-aprendiz.fxml, src/interfaz_usuario/recursos_compartidos/menus/menu_auxiliares/registrar/registrar-usuario.fxml
se hizo refactor al menu medico con camelCase y se realizo dso juevos registrar guardado en recuros compartidos,registrar nuevo usuario y registraraprendiz
=> feat-refactor(MenuMedico)

build/classes/interfaz_usuario/administrador/medico/menu_auxiliares/registrar/registrar-examen-medico.fxml, build/classes/interfaz_usuario/administrador/sistema/menu-auxiliares/ver-mas/menu-ver-mas-clinicas.fxml, build/classes/interfaz_usuario/medico/menu_auxiliares/registrar/registrar-examen-medico.fxml, src/gestor_interfaces/GestorEscenas.java, src/gestor_tablas/GestorTablas.java, src/interfaz_usuario/administrador/sistema/controladores/ControladorVerMasClinicas.java, src/interfaz_usuario/administrador/sistema/menu-auxiliares/ver-mas/menu-ver-mas-clinicas.fxml
Ya se visualizan los datos en el ver mas Clinicas(Exceptuando los datos que son tomados de las funciones en la base de datos aun sin implementar)
=> feat:Funcionalidad del ver mas Clinicas

build/classes/interfaz_usuario/administrador/sistema/menu-auxiliares/ver-mas/menu-ver-mas-autoescuelas.fxml, src/gestor_interfaces/GestorEscenas.java, src/gestor_interfaces/GestorEstadisticas.java, src/gestor_tablas/GestorTablas.java, src/interfaz_usuario/administrador/sistema/controladores/ControladorVerMasAutoescuelas.java, src/interfaz_usuario/administrador/sistema/menu-auxiliares/ver-mas/menu-ver-mas-autoescuelas.fxml
visualizacion del ver mas autoescuela con los datos de la base de datos(Exceptuando los que se hayan a partir de funciones de la base de datos aun por implementar)
=> feat: funcionamiento del ver mas Autoescuela

build/classes/interfaz_usuario/administrador/autoescuela/inicio-admin-autoescuela.fxml, build/classes/interfaz_usuario/administrador/medico/inicio-admin-medico.fxml, build/classes/interfaz_usuario/administrador/sistema/inicio-administrador.fxml, build/classes/interfaz_usuario/recursos_compartidos/menus/menu_auxiliares/registrar/registrar-conductor.fxml, build/classes/interfaz_usuario/recursos_compartidos/menus/menu_auxiliares/registrar/registrar-examen.fxml, build/classes/interfaz_usuario/recursos_compartidos/menus/menu_auxiliares/registrar/registrar-infraccion.fxml, src/interfaz_usuario/administrador/autoescuela/controladores/ControladorAdministradorAutoescuela.java, src/interfaz_usuario/administrador/autoescuela/inicio-admin-autoescuela.fxml, src/interfaz_usuario/administrador/medico/controladores/ControladorAdministradorMedico.java, src/interfaz_usuario/administrador/medico/inicio-admin-medico.fxml
se realizo el refactor a la notacion camelCase a las clases controladores de los menus de administrador autoescuela y administrador medico
=> refactor(Administradorautoescuela-administradormedico)

build/classes/interfaz_usuario/administrador/sistema/inicio-administrador.fxml, build/classes/interfaz_usuario/administrador/sistema/menu-auxiliares/registrar/registrar-autoescuela.fxml, build/classes/interfaz_usuario/administrador/sistema/menu-auxiliares/registrar/registrar-clinica.fxml, build/classes/interfaz_usuario/administrador/sistema/menu-auxiliares/ver-mas/menu-ver-mas-autoescuelas.fxml, build/classes/interfaz_usuario/administrador/sistema/menu-auxiliares/ver-mas/menu-ver-mas-clinicas.fxml, build/classes/interfaz_usuario/recursos_compartidos/menus/menu_auxiliares/registrar/registrar-examen.fxml, build/classes/interfaz_usuario/recursos_compartidos/menus/menu_auxiliares/registrar/registrar-infraccion.fxml, src/gestor_interfaces/GestorEscenas.java, src/interfaz_usuario/administrador/sistema/controladores/ControladorAdministradorSistema.java, src/interfaz_usuario/administrador/sistema/controladores/ControladorRegistrarAutoescuela.java, src/interfaz_usuario/administrador/sistema/controladores/ControladorRegistrarClinica.java, src/interfaz_usuario/administrador/sistema/controladores/ControladorVerMasAutoescuelas.java, src/interfaz_usuario/administrador/sistema/controladores/ControladorVerMasClinicas.java, src/interfaz_usuario/administrador/sistema/inicio-administrador.fxml, src/interfaz_usuario/administrador/sistema/menu-auxiliares/registrar/registrar-autoescuela.fxml, src/interfaz_usuario/administrador/sistema/menu-auxiliares/registrar/registrar-clinica.fxml, src/interfaz_usuario/administrador/sistema/menu-auxiliares/ver-mas/menu-ver-mas-autoescuelas.fxml, src/interfaz_usuario/administrador/sistema/menu-auxiliares/ver-mas/menu-ver-mas-clinicas.fxml, src/interfaz_usuario/recursos_compartidos/estilos/EstilosComboBox.css, src/interfaz_usuario/recursos_compartidos/estilos/EstilosContextMenu.css, src/interfaz_usuario/recursos_compartidos/menus/controladores/ControladorConfiguracionCentro.java, src/interfaz_usuario/recursos_compartidos/menus/controladores/ControladorRegistrarExamen.java, src/interfaz_usuario/recursos_compartidos/menus/controladores/ControladorRegistrarInfraccion.java, src/interfaz_usuario/recursos_compartidos/menus/controladores/ControladorRegistrarUsuario.java, src/interfaz_usuario/recursos_compartidos/menus/menu_auxiliares/registrar/registrar-examen.fxml, src/interfaz_usuario/recursos_compartidos/menus/menu_auxiliares/registrar/registrar-infraccion.fxml, src/interfaz_usuario/recursos_compartidos/menus/menu_configuracion/menu-configuracion-centro.fxml, src/logica/entidad/implementaciones/ServicioEntidad.java, src/logica/validaciones_generales/ValidacionComboBoxVacio.java, src/logica/validaciones_generales/ValidacionGrupoRadioButton.java
se agrego la funcionalidad de registrar con validaciones hechas en todos los registrar de administrador tmb se hizo el informacion del centro en el boton de configuracion del menu inicio y se mejoro la funcionalidad del correo
=> feat(Registrar(Todos))

src/gestor_interfaces/GestorEscenas.java, src/gestor_interfaces/GestorFXML.java, src/interfaz_usuario/administrador/sistema/controladores/ControladorAdministradorSistema.java, src/interfaz_usuario/recursos_compartidos/menus/controladores/ControladorMenuReportesPeriodo.java, src/interfaz_usuario/recursos_compartidos/menus/controladores/ControladorMenuReportesTipo.java, src/interfaz_usuario/recursos_compartidos/menus/menu_reportes_periodo/menu-reportes-infraccion.fxml
se realizo un nuevo controlador y una nueva funcion en el gestor escenas para cargar este menu solo falta la implementacion del reporte de infracciones por tipo
=> feat(MenuReportesTipo)

src/interfaz_usuario/administrador/sistema/controladores/ControladorAdministradorSistema.java, src/interfaz_usuario/recursos_compartidos/estilos/EstilosListView.css, src/interfaz_usuario/recursos_compartidos/menus/controladores/ControladorMenuReportesTipo.java, src/logica/examen_medico/consultas/ConsultaExamenMedico.java, src/logica/examen_medico/implementaciones/ServiciosExamenesMedicos.java
se arreglo el hover de los botones del menuconfiguracion del inicio administrador y se realizo la consulta para obtener la fecha mas vieja de los examenes
=> fix(ReporteCentro)

build/classes/interfaz_usuario/login/login.fxml, src/gestor_interfaces/GestorEscenas.java, src/interfaz_usuario/login/controladores/ControladorLogin.java, src/interfaz_usuario/login/login.fxml, src/interfaz_usuario/recursos_compartidos/menus/controladores/ControladorRegistrarUsuario.java, src/interfaz_usuario/recursos_compartidos/menus/menu_auxiliares/registrar/registrar-usuario.fxml
se realizo nueva funcion en el gestor escenas para mostrar y ocultar contrasennas se aplico en el login y en el registrar usuario
=> feat(MostrarOcultarContra)

build/classes/interfaz_usuario/administrador/sistema/inicio-administrador.fxml, build/classes/interfaz_usuario/recursos_compartidos/menus/menu_auxiliares/registrar/registrar-examen.fxml, build/classes/interfaz_usuario/recursos_compartidos/menus/menu_auxiliares/ver-mas/menu-ver-mas-examenes.fxml, build/classes/interfaz_usuario/recursos_compartidos/menus/menu_auxiliares/ver-mas/menu-ver-mas-licencias.fxml, src/gestor_interfaces/GestorEscenas.java, src/gestor_interfaces/GestorFXML.java, src/gestor_tablas/GestorTablas.java, src/interfaz_usuario/administrador/sistema/controladores/ControladorAdministradorSistema.java, src/interfaz_usuario/administrador/sistema/inicio-administrador.fxml, src/interfaz_usuario/recursos_compartidos/errores/mensaje-cerrar-sesion.fxml, src/interfaz_usuario/recursos_compartidos/estilos/EstilosTableView.css, src/interfaz_usuario/recursos_compartidos/menus/controladores/ControladorMenuReportesPeriodo.java, src/interfaz_usuario/recursos_compartidos/menus/controladores/ControladorMenuReportesTipo.java, src/interfaz_usuario/recursos_compartidos/menus/controladores/ControladorVerMasExamenes.java, src/interfaz_usuario/recursos_compartidos/menus/menu_auxiliares/registrar/registrar-examen.fxml, src/interfaz_usuario/recursos_compartidos/menus/menu_auxiliares/ver-mas/menu-ver-mas-examenes.fxml, src/interfaz_usuario/recursos_compartidos/menus/menu_auxiliares/ver-mas/menu-ver-mas-licencias.fxml, src/logica/excel_gestor/GestorExcel.java
funcionalidad del boton cerrar sesion con menu,agregue rutas al gestor FXML,hice refactor del controlador ver mas examenes
=> feat(BotonCerrarSesion)

build/classes/interfaz_usuario/administrador/sistema/inicio-administrador.fxml, src/gestor_tablas/GestorTablas.java, src/interfaz_usuario/administrador/sistema/controladores/ControladorAdministradorSistema.java, src/interfaz_usuario/administrador/sistema/inicio-administrador.fxml, src/logica/infraccion/implementaciones/ServicioInfraccion.java
se realizo la funcionalidad en el menu entidades y menu infracciones el filtrado de las tablas,corregidas las columnas de esos dos menus ,agregada funcion para limpiar filtros
=> feat(FiltradoEntidades,Infraccion)

build/classes/interfaz_usuario/administrador/sistema/inicio-administrador.fxml, build/classes/interfaz_usuario/administrador/sistema/menu-auxiliares/ver-mas/menu-ver-mas-autoescuelas.fxml, build/classes/interfaz_usuario/administrador/sistema/menu-auxiliares/ver-mas/menu-ver-mas-clinicas.fxml, build/classes/interfaz_usuario/trabajador_autoescuela/inicio-trabajador.fxml, build/classes/interfaz_usuario/trabajador_autoescuela/menu_auxiliares/registrar/registrar-examen-teorico.fxml, build/classes/interfaz_usuario/trabajador_autoescuela/menu_auxiliares/ver-mas/menu-ver-mas-examenes-practicos.fxml, build/classes/interfaz_usuario/trabajador_autoescuela/menu_auxiliares/ver-mas/menu-ver-mas-examenes-teoricos.fxml, nbproject/project.properties, src/gestor_interfaces/GestorEscenas.java, src/gestor_tablas/GestorTablas.java, src/interfaz_usuario/administrador/sistema/controladores/ControladorAdministradorSistema.java, src/interfaz_usuario/administrador/sistema/inicio-administrador.fxml, src/interfaz_usuario/administrador/sistema/menu-auxiliares/ver-mas/menu-ver-mas-autoescuelas.fxml, src/interfaz_usuario/administrador/sistema/menu-auxiliares/ver-mas/menu-ver-mas-clinicas.fxml, src/interfaz_usuario/recursos_compartidos/menus/menu_auxiliares/ver-mas/menu-ver-mas-examenes.fxml, src/interfaz_usuario/trabajador_autoescuela/controladores/ControladorRegistrarExamenTeorico.java, src/interfaz_usuario/trabajador_autoescuela/controladores/ControladorTrabajadorAutoescuela.java, src/interfaz_usuario/trabajador_autoescuela/inicio-trabajador.fxml, src/interfaz_usuario/trabajador_autoescuela/menu_auxiliares/registrar/registrar-examen-teorico.fxml, src/interfaz_usuario/trabajador_autoescuela/menu_auxiliares/ver-mas/menu-ver-mas-examenes-practicos.fxml, src/interfaz_usuario/trabajador_autoescuela/menu_auxiliares/ver-mas/menu-ver-mas-examenes-teoricos.fxml, src/logica/examen_conduccion/implementaciones/ServiciosExamenesConduccion.java, src/logica/persona/implementaciones/ServicioConductor.java
se realizp el filtrado de conductores en el menu administrador,se realizo funcionaldiad de registrar examen teorico en el menutrabajador autoescuela igual q sus dos filtrados en examen teorico y practico
=> feat(FiltradoConductores)
